import './globals.css'
import { Inter } from 'next/font/google'



export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className="bg-zinc-700 h-screen shadow-2xl">{children}</body>
    </html>
  )
}
